### ISSUE TITLE
Problem for "weekday_short" in French

### ISSUE THREAD

**Issue by TitouBilou** [PatriceG/MMM-MPR121#1]
Hi There,
First, thanks very much for this modified version of the RedNax67 module.
When the config.language of MagicMirror is French (my case), the forecast.day label "Fri" (Friday) is translated into "Vend" (Vendredi). This is the only day of the week which translated in French uses 4 letters. Any idea how to change "Vend" into "Ven" (basically, how to get back to the three letters code) ?
Thanks in advance,
Kind regards,
TitouBilou.

**Comment by PatriceG** [comment]
I'm sorry I don't see how this can be related to the MMM-MPR121 module.
